### ISSUE TITLE
App crash after click on Proceed button

### ISSUE THREAD

**Issue by akmalazlanjamal** [MOLPay/Mobile_SDK-Android#4]
I choose Maybank inside payment option, after that click on Proceed button. Then app crash returned stack like below. Please help.

08-11 13:28:49.204    4407-4407/com.molpay.molpayexample E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.NoSuchMethodError: android.support.v4.content.ContextCompat.getDrawable
            at com.molpay.molpaylib.PaymentWebViewFrag.onCreateView(PaymentWebViewFrag.java:178)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:938)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1115)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1478)
            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:446)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by MedetZhakupov** [comment]
To solve the issue please use 22.0.0 and above version of support v4 library in your project
